import SideBar from "@/components/SideBar/SideBar";
import "./globals.css";
import { Inter } from "next/font/google";
import Toast from "@/components/UI/Toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Twitter Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} overscroll-none`}>
        <div className="flex">
          <header className="grow flex justify-end w-[275px]">
            <SideBar />
          </header>
          <div className="grow">{children}</div>
          <Toast />
        </div>
      </body>
    </html>
  );
}
